# Detekt Configuration for KMP POC
# Clean code analysis for Kotlin Multiplatform

build:
  maxIssues: -1 # Allow unlimited issues for now

style:
  active: true
  MagicNumber:
    active: false # Allow magic numbers in UI code
  MaxLineLength:
    active: true
    maxLineLength: 120

naming:
  active: true
  FunctionNaming:
    active: true
    ignoreAnnotated: ['Composable'] # Allow PascalCase for @Composable functions
  ClassNaming:
    active: true

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  ComplexMethod:
    active: true
    threshold: 15

performance:
  active: true

potential-bugs:
  active: true

coroutines:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false # Allow catching Exception in repository layer
